[package]
name = "tui_widgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
crossterm = "0.26.1"

[dev-dependencies]
serial_test = "2.0.0"
